"""core tables: leads, conversations, turns, messages, funnel_transitions,
availability, bookings, turn_metrics

Written by hand rather than autogenerated. Autogenerate does not emit partial
indexes (`postgresql_where`), and the two partial indexes here -- one live
conversation per lead, and inbound message dedup -- are load-bearing
constraints rather than performance hints.

Revision ID: 0001_core_tables
Revises:
Create Date: 2026-08-28
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_core_tables"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

STAGES = (
    "NEW",
    "OPENER",
    "VALUE",
    "TRANSITION",
    "SLOT_FILLING",
    "AWAITING_CONFIRMATION",
    "BOOKED",
    "ABANDONED",
    "OPTED_OUT",
    "HANDED_OFF",
)

# VARCHAR rather than a native Postgres ENUM. See decision D7.
# create_constraint=False: the CHECK is written explicitly below so each one
# gets a distinct name -- funnel_transitions has three stage columns, and
# SQLAlchemy would name all three after the shared type.
stage_type = sa.Enum(*STAGES, native_enum=False, create_constraint=False, length=32, name="funnel_stage")

STAGES_SQL = ", ".join(f"'{s}'" for s in STAGES)
TERMINAL_SQL = "'BOOKED', 'ABANDONED', 'OPTED_OUT', 'HANDED_OFF'"


def _stage_check(column: str, name: str, nullable: bool = False) -> sa.CheckConstraint:
    predicate = f"{column} IN ({STAGES_SQL})"
    if nullable:
        predicate = f"{column} IS NULL OR {predicate}"
    return sa.CheckConstraint(predicate, name=name)


def upgrade() -> None:
    op.create_table(
        "leads",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("channel", sa.String(32), nullable=False),
        sa.Column("channel_user_id", sa.String(128), nullable=False),
        sa.Column("source", sa.String(64), nullable=True),
        sa.Column("display_name", sa.String(128), nullable=True),
        sa.Column("opted_out_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.UniqueConstraint("channel", "channel_user_id", name="uq_leads_channel_user"),
    )

    op.create_table(
        "conversations",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "lead_id",
            sa.Uuid(),
            sa.ForeignKey("leads.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("stage", stage_type, nullable=False, server_default="NEW"),
        sa.Column("locale", sa.String(8), nullable=False, server_default="en"),
        sa.Column(
            "summary", postgresql.JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")
        ),
        sa.Column(
            "slots", postgresql.JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")
        ),
        sa.Column("agent_turn_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column(
            "started_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("last_inbound_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("agent_turn_count >= 0", name="ck_conversations_turn_count"),
        _stage_check("stage", "ck_conversations_stage"),
    )
    # At most one non-terminal conversation per lead.
    op.create_index(
        "uq_conversations_one_live_per_lead",
        "conversations",
        ["lead_id"],
        unique=True,
        postgresql_where=sa.text(f"stage NOT IN ({TERMINAL_SQL})"),
    )

    op.create_table(
        "turns",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "conversation_id",
            sa.Uuid(),
            sa.ForeignKey("conversations.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("agent_turn_index", sa.Integer(), nullable=False),
        sa.Column(
            "started_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.UniqueConstraint("conversation_id", "agent_turn_index", name="uq_turns_conv_index"),
        sa.CheckConstraint("agent_turn_index >= 1", name="ck_turns_index_positive"),
    )

    op.create_table(
        "messages",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "conversation_id",
            sa.Uuid(),
            sa.ForeignKey("conversations.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "turn_id", sa.Uuid(), sa.ForeignKey("turns.id", ondelete="SET NULL"), nullable=True
        ),
        sa.Column("channel", sa.String(32), nullable=False),
        sa.Column("channel_message_id", sa.String(128), nullable=True),
        sa.Column("direction", sa.String(8), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("direction IN ('INBOUND', 'OUTBOUND')", name="ck_messages_direction"),
    )
    # Inbound dedup. Partial, so the many NULL channel_message_ids on outbound
    # CLI messages do not collide.
    op.create_index(
        "uq_messages_channel_msgid",
        "messages",
        ["channel", "channel_message_id"],
        unique=True,
        postgresql_where=sa.text("channel_message_id IS NOT NULL"),
    )
    op.create_index(
        "ix_messages_conversation_created", "messages", ["conversation_id", "created_at"]
    )

    op.create_table(
        "funnel_transitions",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "conversation_id",
            sa.Uuid(),
            sa.ForeignKey("conversations.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "turn_id", sa.Uuid(), sa.ForeignKey("turns.id", ondelete="SET NULL"), nullable=True
        ),
        sa.Column("from_stage", stage_type, nullable=False),
        sa.Column("proposed_stage", stage_type, nullable=True),
        sa.Column("decided_stage", stage_type, nullable=False),
        sa.Column("accepted", sa.Boolean(), nullable=False),
        sa.Column("guard_result", sa.String(64), nullable=True),
        sa.Column("override_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        _stage_check("from_stage", "ck_funnel_transitions_from_stage"),
        _stage_check("proposed_stage", "ck_funnel_transitions_proposed_stage", nullable=True),
        _stage_check("decided_stage", "ck_funnel_transitions_decided_stage"),
    )
    op.create_index("ix_funnel_transitions_conversation", "funnel_transitions", ["conversation_id"])

    op.create_table(
        "availability",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("coach_id", sa.String(64), nullable=False),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_min", sa.Integer(), nullable=False, server_default="30"),
        sa.Column("state", sa.String(16), nullable=False, server_default="FREE"),
        sa.UniqueConstraint("coach_id", "start_at", name="uq_availability_coach_start"),
        sa.CheckConstraint("state IN ('FREE', 'HELD', 'BOOKED')", name="ck_availability_state"),
        sa.CheckConstraint("duration_min > 0", name="ck_availability_duration"),
    )
    op.create_index("ix_availability_lookup", "availability", ["coach_id", "state", "start_at"])

    op.create_table(
        "bookings",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "conversation_id",
            sa.Uuid(),
            sa.ForeignKey("conversations.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("coach_id", sa.String(64), nullable=False),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_min", sa.Integer(), nullable=False, server_default="30"),
        sa.Column("customer_name", sa.String(128), nullable=False),
        sa.Column("phone_e164", sa.String(24), nullable=False),
        sa.Column("idempotency_key", sa.String(128), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        # Double-booking is impossible at the database, not merely unlikely in
        # application code.
        sa.UniqueConstraint("coach_id", "start_at", name="uq_bookings_coach_start"),
        # A retried commit_booking returns the same receipt instead of a second row.
        sa.UniqueConstraint("idempotency_key", name="uq_bookings_idempotency"),
    )

    op.create_table(
        "turn_metrics",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "conversation_id",
            sa.Uuid(),
            sa.ForeignKey("conversations.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "turn_id", sa.Uuid(), sa.ForeignKey("turns.id", ondelete="SET NULL"), nullable=True
        ),
        sa.Column("node", sa.String(48), nullable=False),
        sa.Column("provider", sa.String(32), nullable=True),
        sa.Column("model", sa.String(64), nullable=True),
        sa.Column("schema_mode", sa.String(16), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("tokens_in", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("tokens_out", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("tool_calls", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("repair_attempts", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("first_attempt_valid", sa.Boolean(), nullable=True),
        sa.Column("interrupted", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("locale", sa.String(8), nullable=False, server_default="en"),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.CheckConstraint(
            "schema_mode IS NULL OR schema_mode IN ('native', 'prompt')",
            name="ck_turn_metrics_schema_mode",
        ),
    )
    op.create_index("ix_turn_metrics_conversation", "turn_metrics", ["conversation_id"])
    op.create_index("ix_turn_metrics_node", "turn_metrics", ["node"])


def downgrade() -> None:
    op.drop_table("turn_metrics")
    op.drop_table("bookings")
    op.drop_table("availability")
    op.drop_table("funnel_transitions")
    op.drop_table("messages")
    op.drop_table("turns")
    op.drop_table("conversations")
    op.drop_table("leads")
